# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mozzart Bet Zadatak' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Mozzart Bet Zadatak
    pod 'MBProgressHUD'
    pod 'RestKit', '~> 0.26.0'
    pod 'SDWebImage', '~>3.7'
    pod 'Toast', '~> 3.0'

  target 'Mozzart Bet ZadatakTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Mozzart Bet ZadatakUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
